# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deployDevelopment:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - ""
      - run: 
         name: "Deploy Aplicacion 1"
         command: |
            cd ./Aplicacion1
            yarn run build
            ssh -o StrictHostKeyChecking=no ubuntu@3.223.125.157 "mkdir -p App1"
            scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@3.223.125.157:~/App1
      - run: 
         name: "Deploy Aplicacion 2"
         command: |
            cd ./Aplicacion2
            yarn run build
            ssh -o StrictHostKeyChecking=no ubuntu@3.223.125.157 "mkdir -p App2"
            scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@3.223.125.157:~/App2
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  productionDeploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - ""
      - run: 
         name: "Deploy Aplicacion 1"
         command: |
            cd ./Aplicacion1
            yarn run build
            ssh -o StrictHostKeyChecking=no ubuntu@34.201.47.241 "mkdir -p App1"
            scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@34.201.47.241:~/App1
      - run: 
         name: "Deploy Aplicacion 2"
         command: |
            cd ./Aplicacion2
            yarn run build
            ssh -o StrictHostKeyChecking=no ubuntu@34.201.47.241 "mkdir -p App2"
            scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@34.201.47.241:~/App2
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

 
    


workflows:
  version: 2
  normal_run:
    jobs:
      - deployDevelopment:
          filters:
            branches:
              only:
                - master
      - request-testing:
          type: approval
          requires:
            - deployDevelopment
      - productionDeploy:
          requires:
            - request-testing
          filters:
            branches:
              only:
                - master  